platform :ios, '12.0'
use_frameworks!

def available_pods
  pod 'Kingfisher'
  pod 'iCarousel'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'RxDataSources', '~> 5.0'
end

target 'JKOShop' do
  available_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    # some older pods don't support some architectures, anything over iOS 11 resolves that
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
